const menus = {
	general: {
		list: [
			{ name: "PERFORMANCE", childMenu: "performance" }, 
			{ name: "CUSTOMIZATION", childMenu: "customization" }, 
			{ name: "STANCE", childMenu: "stance" },
		],
		activeElement: 0,
	},
	customization: {
		list: [
			{ name: "BODY", childMenu: "body" }, 
			{ name: "HORNS" }, 
			{ name: "PAINT & WRAP", childMenu: "paint" },
			{ name: "EFFECTS" },
		],
		activeElement: 0,
		parentMenu: "general"
	},
	body: {
		list: [
			{ name: "SPOILER", childMenu: "spoiler" }, 
			{ name: "FRONTBUMPER", childMenu: "frontbumper" }, 
			{ name: "REARBUMPER", childMenu: "rearbumper" },
			{ name: "SIDESKIRT", childMenu: "sideskirt" },
			{ name: "HOOD", childMenu: "hood" },
		],
		activeElement: 0,
		parentMenu: "customization"
	},
	performance: {
		list: [
			{ name: "ENGINE", childMenu: "engine" }, 
			{ name: "TRANSMISSION", childMenu: "transmission" }, 
			{ name: "SUSPENSION", childMenu: "suspension" },
			{ name: "BRAKES", childMenu: "brakes" },
			{ name: "TURBO" },
		],
		activeElement: 0,
		parentMenu: "general"
	},
	engine: {
		list: [
			{ name: "STOCK", type: 'upgrade', price: 1000 }, 
			{ name: "STREET", type: 'upgrade', price: 1000 }, 
			{ name: "PRO", type: 'upgrade', price: 1000 },
			{ name: "ELITE", type: 'upgrade', price: 1000 },
			{ name: "ULTIMATE", type: 'upgrade', price: 1000 },
		],
		activeElement: 0,
		parentMenu: "performance"
	},
	paint: {
		list: [{}],
		activeElement: 0,
		parentMenu: "customization"
	},
    stance: {
		list: [{}],
		activeElement: 0,
		parentMenu: "general"
	},
}

const menuList = ['general', 'customization', 'performance', 'engine', 'transmission', 'suspension', 'brakes', 'spoiler', 'frontbumper', 'rearbumper', 'sideskirt', 'hood', 'paint'];
const staticMenus = ['general', 'customization', 'performance', 'paint', 'stance', 'body'];

const colorsList = [
	{ index: 0, name: 'black'},
    { index: 1, name: 'graphite'},
    { index: 2, name: 'black_metallic'},
    { index: 3, name: 'caststeel'},
    { index: 11, name: 'black_anth'},
    { index: 12, name: 'matteblack'},
    { index: 15, name: 'darknight'},
    { index: 16, name: 'deepblack'},
    { index: 21, name: 'oil'},
    { index: 147, name: 'carbon'},
    { index: 106, name: 'vanilla'},
    { index: 107, name: 'creme'},
    { index: 111, name: 'white'},
    { index: 112, name: 'polarwhite'},
    { index: 113, name: 'beige'},
    { index: 121, name: 'mattewhite'},
    { index: 122, name: 'snow'},
    { index: 131, name: 'cotton'},
    { index: 132, name: 'alabaster'},
    { index: 134, name: 'purewhite'},
    { index: 4, name: 'silver'},
    { index: 5, name: 'metallicgrey'},
    { index: 6, name: 'laminatedsteel'},
    { index: 7, name: 'darkgray'},
    { index: 8, name: 'rockygray'},
    { index: 9, name: 'graynight'},
    { index: 10, name: 'aluminum'},
    { index: 13, name: 'graymat'},
    { index: 14, name: 'lightgrey'},
    { index: 17, name: 'asphaltgray'},
    { index: 18, name: 'grayconcrete'},
    { index: 19, name: 'darksilver'},
    { index: 20, name: 'magnesite'},
    { index: 22, name: 'nickel'},
    { index: 23, name: 'zinc'},
    { index: 24, name: 'dolomite'},
    { index: 25, name: 'bluesilver'},
    { index: 26, name: 'titanium'},
    { index: 66, name: 'steelblue'},
    { index: 93, name: 'champagne'},
    { index: 144, name: 'grayhunter'},
    { index: 156, name: 'grey'},
    { index: 27, name: 'red'},
    { index: 28, name: 'torino_red'},
    { index: 29, name: 'poppy'},
    { index: 30, name: 'copper_red'},
    { index: 31, name: 'cardinal'},
    { index: 32, name: 'brick'},
    { index: 33, name: 'garnet'},
    { index: 34, name: 'cabernet'},
    { index: 35, name: 'candy'},
    { index: 39, name: 'matte_red'},
    { index: 40, name: 'dark_red'},
    { index: 43, name: 'red_pulp'},
    { index: 44, name: 'bril_red'},
    { index: 46, name: 'pale_red'},
    { index: 143, name: 'wine_red'},
    { index: 150, name: 'volcano'},
    { index: 135, name: 'electricpink'},
    { index: 136, name: 'salmon'},
    { index: 137, name: 'sugarplum'},
    { index: 54, name: 'topaz'},
    { index: 60, name: 'light_blue'},
    { index: 61, name: 'galaxy_blue'},
    { index: 62, name: 'dark_blue'},
    { index: 63, name: 'azure'},
    { index: 64, name: 'navy_blue'},
    { index: 65, name: 'lapis'},
    { index: 67, name: 'blue_diamond'},
    { index: 68, name: 'surfer'},
    { index: 69, name: 'pastel_blue'},
    { index: 70, name: 'celeste_blue'},
    { index: 73, name: 'rally_blue'},
    { index: 74, name: 'blue_paradise'},
    { index: 75, name: 'blue_night'},
    { index: 77, name: 'cyan_blue'},
    { index: 78, name: 'cobalt'},
    { index: 79, name: 'electric_blue'},
    { index: 80, name: 'horizon_blue'},
    { index: 82, name: 'metallic_blue'},
    { index: 83, name: 'aquamarine'},
    { index: 84, name: 'blue_agathe'},
    { index: 85, name: 'zirconium'},
    { index: 86, name: 'spinel'},
    { index: 87, name: 'tourmaline'},
    { index: 127, name: 'paradise'},
    { index: 140, name: 'bubble_gum'},
    { index: 141, name: 'midnight_blue'},
    { index: 146, name: 'forbidden_blue'},
    { index: 157, name: 'glacier_blue'},
    { index: 42, name: 'yellow'},
    { index: 88, name: 'wheat'},
    { index: 89, name: 'raceyellow'},
    { index: 91, name: 'paleyellow'},
    { index: 126, name: 'lightyellow'},
    { index: 49, name: 'met_dark_green'},
    { index: 50, name: 'rally_green'},
    { index: 51, name: 'pine_green'},
    { index: 52, name: 'olive_green'},
    { index: 53, name: 'light_green'},
    { index: 55, name: 'lime_green'},
    { index: 56, name: 'forest_green'},
    { index: 57, name: 'lawn_green'},
    { index: 58, name: 'imperial_green'},
    { index: 59, name: 'green_bottle'},
    { index: 92, name: 'citrus_green'},
    { index: 125, name: 'green_anis'},
    { index: 128, name: 'khaki'},
    { index: 133, name: 'army_green'},
    { index: 151, name: 'dark_green'},
    { index: 152, name: 'hunter_green'},
    { index: 155, name: 'matte_foilage_green'},
    { index: 36, name: 'tangerine'},
    { index: 38, name: 'orange'},
    { index: 41, name: 'matteorange'},
    { index: 123, name: 'lightorange'},
    { index: 124, name: 'peach'},
    { index: 130, name: 'pumpkin'},
    { index: 138, name: 'orangelambo'},
    { index: 45, name: 'copper'},
    { index: 47, name: 'lightbrown'},
    { index: 48, name: 'darkbrown'},
    { index: 90, name: 'bronze'},
    { index: 94, name: 'brownmetallic'},
    { index: 95, name: 'Expresso'},
    { index: 96, name: 'chocolate'},
    { index: 97, name: 'terracotta'},
    { index: 98, name: 'marble'},
    { index: 99, name: 'sand'},
    { index: 100, name: 'sepia'},
    { index: 101, name: 'bison'},
    { index: 102, name: 'palm'},
    { index: 103, name: 'caramel'},
    { index: 104, name: 'rust'},
    { index: 105, name: 'chestnut'},
    { index: 108, name: 'brown'},
    { index: 109, name: 'hazelnut'},
    { index: 110, name: 'shell'},
    { index: 114, name: 'mahogany'},
    { index: 115, name: 'cauldron'},
    { index: 116, name: 'blond'},
    { index: 129, name: 'gravel'},
    { index: 153, name: 'darkearth'},
    { index: 154, name: 'desert'},
    { index: 71, name: 'indigo'},
    { index: 72, name: 'deeppurple'},
    { index: 76, name: 'darkviolet'},
    { index: 81, name: 'amethyst'},
    { index: 142, name: 'mysticalviolet'},
    { index: 145, name: 'purplemetallic'},
    { index: 148, name: 'matteviolet'},
    { index: 149, name: 'mattedeeppurple'},
    { index: 117, name: 'brushechrome'},
    { index: 118, name: 'blackchrome'},
    { index: 119, name: 'brushedaluminum'},
    { index: 120, name: 'chrome'},
    { index: 37, name: 'gold'},
    { index: 158, name: 'puregold'},
    { index: 159, name: 'brushedgold'},
    { index: 160, name: 'lightgold'},
];

const paintTypes = ['primary', 'secondary', 'pearlescent', 'wheels'];

const sliders = [
    {
        "label": "FRONT CAMBER",
        "name": "frontcamber",
        "min": -0.19,
        "max": 0.19,
        "current": 0.0,
    },
    {
        "label": "FRONT WIDTH",
        "name": "frontwidth",
        "min": -0.19,
        "max": 0.19,
        "current": 0.0,
    },
    {
        "label": "REAR CAMBER",
        "name": "rearcamber",
        "min": -0.19,
        "max": 0.19,
        "current": 0.0,
    },
    {
        "label": "REAR WIDTH",
        "name": "rearwidth",
        "min": -0.19,
        "max": 0.19,
        "current": 0.0,
    },
];

const sliderConfig = {
    step: 0.01,
};

export { menus, menuList, staticMenus, colorsList, paintTypes, sliders, sliderConfig }