const menus = {
	general: {
		list: [
			{ name: "PERFORMANCE", childMenu: "performance" }, 
			{ name: "CUSTOMIZATION", childMenu: "customization" }, 
			{ name: "STANCE", childMenu: "stance" },
		],
		activeElement: 0,
	},
	customization: {
		list: [
			{ name: "BODY", childMenu: "body" }, 
			{ name: "HORNS" }, 
			{ name: "PAINT & WRAP", childMenu: "paint" },
			{ name: "EFFECTS" },
		],
		activeElement: 0,
		parentMenu: "general"
	},
	body: {
		list: [
			{ name: "SPOILER", childMenu: "spoiler" }, 
			{ name: "FRONTBUMPER", childMenu: "frontbumper" }, 
			{ name: "REARBUMPER", childMenu: "rearbumper" },
			{ name: "SIDESKIRT", childMenu: "sideskirt" },
			{ name: "HOOD", childMenu: "hood" },
		],
		activeElement: 0,
		parentMenu: "customization"
	},
	performance: {
		list: [
			{ name: "ENGINE", childMenu: "engine" }, 
			{ name: "TRANSMISSION", childMenu: "transmission" }, 
			{ name: "SUSPENSION", childMenu: "suspension" },
			{ name: "BRAKES", childMenu: "brakes" },
			{ name: "TURBO" },
		],
		activeElement: 0,
		parentMenu: "general"
	},
	engine: {
		list: [
			{ name: "STOCK", type: 'upgrade', price: 1000 }, 
			{ name: "STREET", type: 'upgrade', price: 1000 }, 
			{ name: "PRO", type: 'upgrade', price: 1000 },
			{ name: "ELITE", type: 'upgrade', price: 1000 },
			{ name: "ULTIMATE", type: 'upgrade', price: 1000 },
		],
		activeElement: 0,
		parentMenu: "performance"
	},
	paint: {
		list: [{}],
		activeElement: 0,
		parentMenu: "customization"
	},
    stance: {
		list: [{}],
		activeElement: 0,
		parentMenu: "general"
	},
}

const menuList = ['general', 'customization', 'performance', 'engine', 'transmission', 'suspension', 'brakes', 'spoiler', 'frontbumper', 'rearbumper', 'sideskirt', 'hood', 'paint'];
const staticMenus = ['general', 'customization', 'performance', 'paint', 'stance', 'body'];

const colorsList = [
	{ index: 0, name: 'black'},
    { index: 1, name: 'graphite'},
    { index: 2, name: 'black metallic'},
    { index: 3, name: 'cast steel'},
    { index: 11, name: 'black anth'},
    { index: 12, name: 'matte black'},
    { index: 15, name: 'dark night'},
    { index: 16, name: 'deep black'},
    { index: 21, name: 'oil'},
    { index: 147, name: 'carbon'},
    { index: 106, name: 'vanilla'},
    { index: 107, name: 'creme'},
    { index: 111, name: 'white'},
    { index: 112, name: 'polar white'},
    { index: 113, name: 'beige'},
    { index: 121, name: 'matte white'},
    { index: 122, name: 'snow'},
    { index: 131, name: 'cotton'},
    { index: 132, name: 'alabaster'},
    { index: 134, name: 'pure white'},
    { index: 4, name: 'silver'},
    { index: 5, name: 'metallic grey'},
    { index: 6, name: 'laminated steel'},
    { index: 7, name: 'dark gray'},
    { index: 8, name: 'rocky gray'},
    { index: 9, name: 'gray night'},
    { index: 10, name: 'aluminum'},
    { index: 13, name: 'gray mat'},
    { index: 14, name: 'light grey'},
    { index: 17, name: 'asphalt gray'},
    { index: 18, name: 'gray concrete'},
    { index: 19, name: 'dark silver'},
    { index: 20, name: 'magnesite'},
    { index: 22, name: 'nickel'},
    { index: 23, name: 'zinc'},
    { index: 24, name: 'dolomite'},
    { index: 25, name: 'blue silver'},
    { index: 26, name: 'titanium'},
    { index: 66, name: 'steel blue'},
    { index: 93, name: 'champagne'},
    { index: 144, name: 'gray hunter'},
    { index: 156, name: 'grey'},
    { index: 27, name: 'red'},
    { index: 28, name: 'torino red'},
    { index: 29, name: 'poppy'},
    { index: 30, name: 'copper red'},
    { index: 31, name: 'cardinal'},
    { index: 32, name: 'brick'},
    { index: 33, name: 'garnet'},
    { index: 34, name: 'cabernet'},
    { index: 35, name: 'candy'},
    { index: 39, name: 'matte red'},
    { index: 40, name: 'dark red'},
    { index: 43, name: 'red pulp'},
    { index: 44, name: 'bril red'},
    { index: 46, name: 'pale red'},
    { index: 143, name: 'wine red'},
    { index: 150, name: 'volcano'},
    { index: 135, name: 'electric pink'},
    { index: 136, name: 'salmon'},
    { index: 137, name: 'sugarplum'},
    { index: 54, name: 'topaz'},
    { index: 60, name: 'light blue'},
    { index: 61, name: 'galaxy blue'},
    { index: 62, name: 'dark blue'},
    { index: 63, name: 'azure'},
    { index: 64, name: 'navy blue'},
    { index: 65, name: 'lapis'},
    { index: 67, name: 'blue diamond'},
    { index: 68, name: 'surfer'},
    { index: 69, name: 'pastel blue'},
    { index: 70, name: 'celeste blue'},
    { index: 73, name: 'rally blue'},
    { index: 74, name: 'blue paradise'},
    { index: 75, name: 'blue night'},
    { index: 77, name: 'cyan blue'},
    { index: 78, name: 'cobalt'},
    { index: 79, name: 'electric blue'},
    { index: 80, name: 'horizon blue'},
    { index: 82, name: 'metallic blue'},
    { index: 83, name: 'aquamarine'},
    { index: 84, name: 'blue agathe'},
    { index: 85, name: 'zirconium'},
    { index: 86, name: 'spinel'},
    { index: 87, name: 'tourmaline'},
    { index: 127, name: 'paradise'},
    { index: 140, name: 'bubble gum'},
    { index: 141, name: 'midnight blue'},
    { index: 146, name: 'forbidden blue'},
    { index: 157, name: 'glacier blue'},
    { index: 42, name: 'yellow'},
    { index: 88, name: 'wheat'},
    { index: 89, name: 'race yellow'},
    { index: 91, name: 'pale yellow'},
    { index: 126, name: 'light yellow'},
    { index: 49, name: 'met dark green'},
    { index: 50, name: 'rally green'},
    { index: 51, name: 'pine green'},
    { index: 52, name: 'olive green'},
    { index: 53, name: 'light green'},
    { index: 55, name: 'lime green'},
    { index: 56, name: 'forest green'},
    { index: 57, name: 'lawn green'},
    { index: 58, name: 'imperial green'},
    { index: 59, name: 'green bottle'},
    { index: 92, name: 'citrus green'},
    { index: 125, name: 'green anis'},
    { index: 128, name: 'khaki'},
    { index: 133, name: 'army green'},
    { index: 151, name: 'dark green'},
    { index: 152, name: 'hunter green'},
    { index: 155, name: 'matte foilage green'},
    { index: 36, name: 'tangerine'},
    { index: 38, name: 'orange'},
    { index: 41, name: 'matte orange'},
    { index: 123, name: 'light orange'},
    { index: 124, name: 'peach'},
    { index: 130, name: 'pumpkin'},
    { index: 138, name: 'orange lambo'},
    { index: 45, name: 'copper'},
    { index: 47, name: 'light brown'},
    { index: 48, name: 'dark brown'},
    { index: 90, name: 'bronze'},
    { index: 94, name: 'brown metallic'},
    { index: 95, name: 'Expresso'},
    { index: 96, name: 'chocolate'},
    { index: 97, name: 'terracotta'},
    { index: 98, name: 'marble'},
    { index: 99, name: 'sand'},
    { index: 100, name: 'sepia'},
    { index: 101, name: 'bison'},
    { index: 102, name: 'palm'},
    { index: 103, name: 'caramel'},
    { index: 104, name: 'rust'},
    { index: 105, name: 'chestnut'},
    { index: 108, name: 'brown'},
    { index: 109, name: 'hazelnut'},
    { index: 110, name: 'shell'},
    { index: 114, name: 'mahogany'},
    { index: 115, name: 'cauldron'},
    { index: 116, name: 'blond'},
    { index: 129, name: 'gravel'},
    { index: 153, name: 'darkearth'},
    { index: 154, name: 'desert'},
    { index: 71, name: 'indigo'},
    { index: 72, name: 'deep purple'},
    { index: 76, name: 'dark violet'},
    { index: 81, name: 'amethyst'},
    { index: 142, name: 'mystical violet'},
    { index: 145, name: 'purple metallic'},
    { index: 148, name: 'matte violet'},
    { index: 149, name: 'matte deep purple'},
    { index: 117, name: 'brushe chrome'},
    { index: 118, name: 'black chrome'},
    { index: 119, name: 'brushed aluminum'},
    { index: 120, name: 'chrome'},
    { index: 37, name: 'gold'},
    { index: 158, name: 'pure gold'},
    { index: 159, name: 'brushed gold'},
    { index: 160, name: 'light gold'},
];

const paintTypes = ['primary_color', 'secondary_color', 'pearlescent_color', 'wheels_color'];

const sliders = [
    {
        "label": "FRONT CAMBER",
        "name": "frontcamber",
        "min": -0.19,
        "max": 0.19,
        "current": 0.0,
    },
    {
        "label": "FRONT WIDTH",
        "name": "frontwidth",
        "min": -0.19,
        "max": 0.19,
        "current": 0.0,
    },
    {
        "label": "REAR CAMBER",
        "name": "rearcamber",
        "min": -0.19,
        "max": 0.19,
        "current": 0.0,
    },
    {
        "label": "REAR WIDTH",
        "name": "rearwidth",
        "min": -0.19,
        "max": 0.19,
        "current": 0.0,
    },
];

const sliderConfig = {
    step: 0.01,
};

export { menus, menuList, staticMenus, colorsList, paintTypes, sliders, sliderConfig }