let dotMap = {
  
  spawns: [
    {
      name: "Apartments",
      x: 957,
      y: 268,
      icon: "pin",
      iconSelected: "pinSel",
      image: "images/apartments.png",
      description: "",
    },
    {
      name: "Dashhound Bus Station",
      x: 659,
      y: -451,
      icon: "pin",
      iconSelected: "pinSel",
      image: "images/busstation.png",
      description: "",
    },
    {
      name: "Del Perro Pier",
      x: 1231,
      y: 1838,
      icon: "pin",
      iconSelected: "pinSel",
      image: "images/delperro.png",
      description: "",
    },
    {
      name: "Sandy Shores LSC",
      x: -2642,
      y: -1196,
      icon: "pin",
      iconSelected: "pinSel",
      image: "images/sandylsc.png",
      description: "",
    },
    {
      name: "Pacific Standard Bank",
      x: -216,
      y: -233,
      icon: "pin",
      iconSelected: "pinSel",
      image: "images/pacificstandard.png",
      description: "",
    },
    {
      name: "The Richman Hotel",
      x: -313,
      y: 1275,
      icon: "pin",
      iconSelected: "pinSel",
      image: "images/richmanhotel.png",
      description: "",
    },
    {
      name: "Paleto Bay Hen House",
      x: -6231,
      y: 320,
      icon: "pin",
      iconSelected: "pinSel",
      image: "images/henhouse.png",
      description: "",
    },
    {
      name: "Paleto Bay LSC",
      x: -6608,
      y: -102,
      icon: "pin",
      iconSelected: "pinSel",
      image: "images/paletolsc.png",
      description: "",
    },
  ],
};
